name: "Covid-19 Tracker App by Abdul Moiz Lakhani"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Intall Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
        env:
          REACT_APP_API_HOST: ${{ secrets.REACT_APP_API_HOST }}
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}

      - name: Build React App
        run: sudo yarn build

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy React App to Surge
        run: surge ./build covid-19-tracker-amlakhani.surge.sh --token ${{ secrets.SURGE_TOKEN }}
